version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "Running tests..."
      - npm test
      - echo "Building application..."
      - zip -r function.zip . # Zip the project for Lambda
  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp function.zip s3://livebazaar-deployment/
      - echo "Deploying to Lambda..."
      - aws lambda update-function-code --function-name LiveBazaarAuth --s3-bucket livebazaar-deployment --s3-key function.zip
