service: lambda-api
provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
