service: live-bazar-api

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-south-1
  deploymentBucket:
    name: live-bazar-deployment-bucket
  environment:
    DYNAMODB_USER_TABLE: UserTable
    DYNAMODB_PRODUCT_TABLE: ProductTable
    DYNAMODB_ORDER_TABLE: OrderTable
    DYNAMODB_SHOPS_TABLE: shops

custom:
  serverless-offline:
    httpPort: 3000
    lambdaTimeout: 300

resources:
  # Include external resources file
  - ${file(./config/resources.yml)}

functions:
  # Include external functions file
  ${file(./config/functions.yml)}

plugins:
  - serverless-offline
  - serverless-plugin-include-dependencies

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - .git/**
    - .vscode/**
    - tests/**
    - README.md
    - package-lock.json
  include:
    - src/**
    - serverless.yml
    - src/models/**
    - src/config/**