service: live-bazar-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  disableDefaultOutputExportNames: true
  disableDefaultOutputExports: true
  useDotenv: false
  disableDefaultIamRoleStatements: true
  deploymentBucket:
    name: your-existing-bucket-name
  environment:
    DYNAMODB_USER_TABLE: UserTable
    DYNAMODB_PRODUCT_TABLE: ProductTable
    DYNAMODB_ORDER_TABLE: OrderTable

configValidationMode: off

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ProductTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ProductTable
        AttributeDefinitions:
          - AttributeName: productId
            AttributeType: S
        KeySchema:
          - AttributeName: productId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    OrderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrderTable
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: S
        KeySchema:
          - AttributeName: orderId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

functions:
  userApi:
    handler: src/handlers/user.handler
    events:
      - http:
          path: user
          method: post
      - http:
          path: user/{id}
          method: get

  productApi:
    handler: src/handlers/product.handler
    events:
      - http:
          path: product
          method: post
      - http:
          path: product/{id}
          method: get

  orderApi:
    handler: src/handlers/order.handler
    events:
      - http:
          path: order
          method: post
      - http:
          path: order/{id}
          method: get

package:
  individually: true
  excludeDevDependencies: true
  exclude:
    - node_modules/aws-sdk/** # Exclude aws-sdk explicitly
    - .git/**                 # Exclude Git files
    - .vscode/**              # Exclude VSCode settings
    - tests/**                # Exclude test files
    - README.md               # Exclude README
    - package-lock.json       # Exclude lock file
  include:
    - src/**                  # Include only source files
    - serverless.yml          # Include serverless configuration

plugins:
  - serverless-offline