userApi:
  handler: src/handlers/user.handler
  timeout: 300
  events:
    - http:
        path: user
        method: post
    - http:
        path: user/{id}
        method: get


shopApi:
  handler: src/handlers/shop.handler
  timeout: 300
  events:
    - http:
        path: shop
        method: post
    - http:
        path: shop/{id}
        method: get
    - http:
        path: shop/{id}
        method: patch
    - http:
        path: shop/{id}
        method: delete
    - http:
        path: shops
        method: get

# categoryApi:
#   handler: src/handlers/category.handler
#   timeout: 300
#   events:
#     - http:
#         path: category
#         method: post
#     - http:
#         path: category/{id}
#         method: get
#     - http:
#         path: category/{id}
#         method: patch
#     - http:
#         path: category/{id}
#         method: delete
#     - http:
#         path: categories
#         method: get

testFunction:
  handler: src/handlers/test.handler
  events:
    - http:
        path: test
        method: get
