categoryApi:
  handler: src/handlers/category.handler
  timeout: 300
  events:
    - http:
        path: category
        method: post
    - http:
        path: category/{id}
        method: get
    - http:
        path: category/{id}
        method: patch
    - http:
        path: category/{id}
        method: delete
    - http:
        path: categories
        method: get

vendorApi:
  handler: src/handlers/vendor.handler
  timeout: 300
  events:
    - http:
        path: vendor
        method: post
    - http:
        path: vendor/{id}
        method: get
    - http:
        path: vendor/{id}
        method: patch
    - http:
        path: vendor/{id}
        method: delete
    - http:
        path: vendors
        method: get
    - http:
        path: vendors-by-city-category
        method: get


productApi:
  handler: src/handlers/product.handler
  timeout: 300
  events:
    - http:
        path: product
        method: post
    - http:
        path: product/{id}
        method: get
    - http:
        path: product/{id}
        method: patch
    - http:
        path: product/{id}
        method: delete
    - http:
        path: products
        method: get
    - http:
        path: products-by-vendor
        method: get

imageUpload:
  handler: src/functions/imageUpload.handler
  events:
    - http:
        path: upload-image
        method: post
        cors: true
        # For multipart/form-data support, use serverless-express or middy
