Resources:
  # UserTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UserTable
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST

  categories:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: categories
      AttributeDefinitions:
        - AttributeName: categoryId
          AttributeType: S
      KeySchema:
        - AttributeName: categoryId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  vendors:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: vendors
      AttributeDefinitions:
        - AttributeName: vendor_id
          AttributeType: S
      KeySchema:
        - AttributeName: vendor_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  products:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: products
      AttributeDefinitions:
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: product_id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST