Resources:
  # UserTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     TableName: UserTable
  #     AttributeDefinitions:
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: userId
  #         KeyType: HASH
  #     BillingMode: PAY_PER_REQUEST

  shops:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: shops
      AttributeDefinitions:
        - AttributeName: shopId
          AttributeType: S
      KeySchema:
        - AttributeName: shopId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
