name: Deploy Lambda API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3name: Deploy Lambda API

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean install production dependencies
        run: npm ci --only=production

      # Optional: If you're building with esbuild/webpack, add a build step here
      # - name: Build the Lambda function
      #   run: npm run build

      - name: Prepare Lambda package
        run: |
          mkdir -p lambda-package
          cp -r index.js package.json node_modules lambda-package/
          cd lambda-package
          zip -r ../function.zip .

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: my-lambda-api
          zip_file: function.zip
          publish: true

        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Zip the Lambda Package
        run: zip -r function.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-south-1
          function_name: my-lambda-api
          zip_file: function.zip
